---
run:
  build-tags:
    - netgo
    - e2e
  concurrency: 6
  deadline: 5m
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- dupl
    - errcheck
    - errorlint
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- exhaustive
    - exportloopref
    - gci
    #- gochecknoinits
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- gocognit
    - goconst
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- gocritic
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- gocyclo
    - godot
    #- godox
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- golint
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- gomnd
    - gomodguard
    #- goprintffuncname
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- gosec
    - gosimple
    - govet
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- ineffassign
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- interfacer
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- lll
    - maligned
    - misspell
    - nakedret
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- nestif
    - noctx
    - nolintlint
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- stylecheck
    - tparallel
    - typecheck
    - unconvert
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- unparam
    - unused
    - varcheck
    - whitespace
    # TODO(jaosorior): Re-enable this in a subsequent PR
    #- wrapcheck
    # - exhaustivestruct
    # - funlen
    # - gochecknoglobals
    # - nlreturn
    # - scopelint
    # - testpackage
    # - wsl
linters-settings:
  gci:
    local-prefixes: sigs.k8s.io/security-profiles-operator
  errcheck:
    check-type-assertions: true
    check-blank: true
  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
  gocritic:
    enabled-checks:
      # Diagnostic
      - appendAssign
      - argOrder
      - badCond
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - flagDeref
      - flagName
      - nilValReturn
      - offBy1
      - sloppyReassign
      - weakCond
      - octalLiteral

      # Performance
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - rangeExprCopy
      - rangeValCopy

      # Style
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - commentedOutImport
      - defaultCaseOrder
      - docStub
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - hexLiteral
      - ifElseChain
      - methodExprCall
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlabelStmt
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc
      - yodaStyleExpr

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnamedResult
      - unnecessaryBlock
