apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compliancechecks.compliance.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.result
    name: Result
    type: string
  group: compliance.openshift.io
  names:
    kind: ComplianceCheck
    listKind: ComplianceCheckList
    plural: compliancechecks
    singular: compliancecheck
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: ComplianceCheck is the Schema for the compliancechecks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ComplianceCheckSpec defines the desired state of ComplianceCheck
          properties:
            description:
              type: string
            id:
              type: string
            result:
              type: string
          required:
          - id
          - result
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
